minimal_mistakes_skin    : "dark"

# Site Settings
locale                   : "en-US"

title: "Parag Bafna"
description: "Expert in Developing Mobile and Desktop Applications"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paragbafna.github.io" # the base hostname & protocol for your site

# Remote theme settings
remote_theme: mmistakes/minimal-mistakes

# Social Links
email: support@paragbafna.com

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

# Navigation
header:
  nav:
    - text: "Home"
      url: "/"
    - text: "Expertise"
      url: "/expertise/"
    - text: "Portfolio"
      url: "/portfolio/"
    - text: "Contact"
      url: "/contact/"

footer:
  links:
    - text: "Support Email"
      url: "mailto:support@paragbafna.com"
    - text: "Office Address: 132 Gopal Nagar, Sagod Road, Ratlam - 457001, Madhya Pradesh, India"

# Build settings
markdown: kramdown
highlighter: rouge

include:
  - _pages
