remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin    : "dark" # Switching to a dark theme for a more professional look

# Site Settings
locale                   : "en-US"
title                    : "Parag Bafna"
title_separator          : "-"
subtitle                 : "Expert in Developing Mobile and Desktop Applications"
name                     : "Parag Bafna"
description              : "Specializing in developing high-quality mobile applications for iOS and desktop applications for macOS."
url                      : "https://paragbafna.com"
baseurl                  : "" # GitHub Pages will handle the base URL
masthead_title           : "Parag Bafna"

footer:
  links:
    - text: "Support Email"
      url: "mailto:support@paragbafna.com"
    - text: "Office Address"
      url: "https://maps.google.com/?q=132 Gopal Nagar, Sagod Road, Ratlam - 457001, Madhya Pradesh, India"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache


# Site Author
author:
  name             : "Parag Bafna"
  bio              : "Expert in developing high-quality mobile and desktop applications."
  location         : "Ratlam, Madhya Pradesh, India"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - .DS_Store
  - __MACOSX
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

# Markdown Processing
markdown: kramdown
highlighter: rouge
